### ISSUE TITLE
Typings

### ISSUE THREAD

**Issue by JPeer264** [JPeer264/node-rcs-core#100]
Either add types or rewrite to Typescript

**Comment by X-Ryl669** [comment]
I thought we already have types here with `class`. What do you mean ?

**Comment by JPeer264** [comment]
I mean a `.d.ts` file so it can be used for a typescript project. For example in https://github.com/JPeer264/rcs-webpack-plugin I would already need types.

**Comment by X-Ryl669** [comment]
Ah, I see. This will need typescript and tsify (to build) in nodejs. That seems like a lot of work to implement through, the project is now very large, but it'll catch even more errors in code.

**Comment by JPeer264** [comment]
Closed due to #106 and #108
