### ISSUE TITLE
[Feature request] Optimize replacement

### ISSUE THREAD

**Issue by X-Ryl669** [JPeer264/node-rcs-core#111]
I'm sorry I'm not more active with this project. 

Anyway, I've seen that you've improved the statistic class.
I wonder if it would be possible to dump the stat for a processing (maybe with some additional option?) and load it for another pass (another option required).

In that case, the replacement map could be optimized to assign the shortest selectors to the most used classes. This is algorithmically easy to implement if done this way:

1. Upon first pass, save the selected selectors (already done in the `renaming_map.json` file)
2. Upon first pass, save the statistics (todo)
3. Upon second pass if loaded with statistics, load all renamed selectors
4. Sort them based on their size (the shortest first)
5. Sort the statistics object based on their size (the higher counter first)
6. Create a map between the *sorted* statistics base selector and the *sorted* renamed selector
7. Patch the `renaming_map` object with the best renamed selector
8. Run the renaming process as usual with the updated `renaming_map`

This should give the maximum compression rate (until we start to rewrite CSS to be the most efficient like changing `a[class=b]` to `a.b`, but that's a whole new can of worms).

**Comment by JPeer264** [comment]
Ah, that's no problem ;) 

Yes, that is actually a pretty smart thing to do! It will take some time for me to implement this though, as I have some little time ATM. But I keep you updated.
