### ISSUE TITLE
How to include class names containing colon

### ISSUE THREAD

**Issue by david-szabo97** [JPeer264/node-rcs-core#122]
How to include class names containing colon?

For example tailwind uses `md:` prefix for classes. How to make sure that `md:flex` is renamed?

**Comment by JPeer264** [comment]
Hey @david-szabo97 , thanks for your issue. Back then I didn't thought this would be a valid use case, but ya there is definitely one. I will add this functionality asap

**Comment by JPeer264** [comment]
@david-szabo97 ok seems like this issue came up in 2018 and has been tested (ref: https://github.com/JPeer264/node-rcs-core/issues/67). Can you tell me which version you use?

**Comment by david-szabo97** [comment]
Sorry! It's my bad. Looks like `purge-css` removed all the classes containing colons. So I thought RCS is not working properly.

Thanks for the quick reply!

**Comment by JPeer264** [comment]
No worries.

I bet it is also nice to work with the `.statistics` from `rcs-core`. We introduced a list of not used selectors here (https://github.com/JPeer264/node-rcs-core/blob/main/docs/api/statistics.md).
