### ISSUE TITLE
Does not prefix classes named after html elements?

### ISSUE THREAD

**Issue by narbehm** [JPeer264/node-rcs-core#145]
Classes such as .h1, .blockquote, .base are not processed. How do you include these for processing? I'm using it to just prefix classes so I want the bootstrap .h1 class to be renamed to .bs-h1

**Comment by JPeer264** [comment]
Sorry for the late response. You can simply add them before you fill your library:

```js
// following includes h1 and blockquote
rcs.selectorsLibrary.setInclude(['h1', 'blockquote']);
rcs.fillLibraries(fs.readFileSync('./src/styles.css', 'utf8'));
```

or you include all again (which I do not recommend):

```js
const excludeList = require('rcs-core/dest/helpers/excludeList');

rcs.selectorsLibrary.setInclude(excludeList);
```
