### ISSUE TITLE
html parsing problem

### ISSUE THREAD

**Issue by Aliaksandr-Padabed** [JPeer264/node-rcs-core#50]
html:
```html
<p class="cl1">text with 'single quote</p>
...
<p class="cl1">another s'ingle quote</p>
```
js:
```javascript
rcs.replace.any(html);
```
result:
```javascript
"cl1|single quote</p>...<p class="cl1">another s"
```

**Comment by JPeer264** [comment]
Hey @Aliaksandr-Padabed, thanks for your issue. 

Oh, that should not happen. I'm gonna investigate this tomorrow.

**Comment by JPeer264** [comment]
@Aliaksandr-Padabed I published now a new function for HTML. Can you try `rcs.replace.html`?

For now this function just replaces `class` and `id` attributes, but I will add more attributes soon (ref: #53).

If this or another error still exists please open a new issue.
