### ISSUE TITLE
feat: warn on unused class names

### ISSUE THREAD

**Issue by Aliaksandr-Padabed** [JPeer264/node-rcs-core#55]
It will be good to have warnings or some statistics on unused classes, this will help developers to clean unused code. 
As I can see it possible to store in Set each class name during parsing and finally compare with collected names.

**Comment by JPeer264** [comment]
Ya, some statistics could be great indeed. This feature is also kinda easy to implement, as you already figured. 

For this feature: is a JSON output in an own function enough? E.g.:

```js
rcs.stats();
// output: 
// {
//   unusedClasses: ['a', 'b', ...],
//   unusedIds: ['a', 'b', ...],
// }
```

Or you thought about another way?

**Comment by Aliaksandr-Padabed** [comment]
looks good except in array should be full names

**Comment by JPeer264** [comment]
Perfect. I'm gonna implement this in the coming week when I have time!
