### ISSUE TITLE
webpack plugin and way to change the regex only in js target files

### ISSUE THREAD

**Issue by ivmarcos** [JPeer264/node-rcs-core#7]
Nice work. I was looking for a webpack plugin and I ended up falling here. It would be interesting to create one besides the gulp and grunt.

In my case, working on a react project, how could I change the regex to match the js target file, since the classname attribute in react is not prefixed by dots? 

`<Component className="class-name-example" />`

**Comment by JPeer264** [comment]
Thanks for your issue. I was indeed planning on a webpack plugin, but I never got time. If you can create one it would be awesome!

**SHORT ANSWER:** `replace.buffer` or `replace.bufferCss` does that for you.

**LONG ANSWER:**
Generally I have two different approaches matching "classes" and "ids". The first one is for CSS files, where everything is prefixed by either a `.` or a `#`. From `rcs-core` the way to replace all variables is `replace.bufferCss`, `replace.fileCss` or `replace.fileCssSync` (depends on what content you got). 

The second is for JS/HTML/... . This method is actually pretty naiv, but I never had any issues in bigger projects. Here there is just a regex matching `' '` or `" "` (single or double quotes). There is a own function for that -> `replace.buffer`, `replace.file` or `replace.fileSync`.

So you do not need to care about regex anymore, as it is already implemented in those functions.

The only problem I have is JS-in-CSS. This library assumes that CSS and JS/HTML/... is separately, (first parses CSS files, then replace other files). My only thoughts for this were process the files twice:
1. Parse the file with `replace.bufferCss`
1. Parse the file **again** with `replace.buffer`

BTW, have in mind, that CSS classes/ids must be processed before it comes to other files. As just the CSS selectors are able to rename those selectors (I hope that was understandable).

**Comment by JPeer264** [comment]
If you haven't already seen those. Here are my used regex: [replace.js#L9](https://github.com/JPeer264/node-rcs-core/blob/c90786098c503251a5083f36db2aeb3dad9153eb/lib/options/replace.js#L9)

**Comment by ivmarcos** [comment]
Sorry, I had not seen it, worked as i thought, perfectly! So easy. I'll try create the plugin, but time here is also short.

Thanks!

Test done:

```
const rcs = require('rcs-core');

const css = `
.test{
  background-color: red
}
.test-two{
  color: rgb(0,0,0)
}
.test-three{
  color: rgb(1,1,1)
}
`;

const js = `
<Component className={'test'}/>
<Component className={'test-two'}/>
<Component className={'test-three'}/>
`

const replacedBuffer = rcs.replace.bufferCss(new Buffer(css));
console.log('replacedBuffer', replacedBuffer.toString('utf-8'));

const replacedBufferJS = rcs.replace.buffer(new Buffer(js));
console.log('replacedBuffer', replacedBufferJS.toString('utf-8'));
```

**Comment by JPeer264** [comment]
@ivmarcos exactly that's how it works 👍  - btw, ping me if you got the plugin done (take your time), I will link it then to my readme, or just do a PR.
