### ISSUE TITLE
Update espree

### ISSUE THREAD

**Issue by klimashkin** [JPeer264/node-rcs-core#73]
Hi @JPeer264!
Seems like it's time to update espree : )
rename-css-selectors fails on optional catch binding in a code (catch without the arguent)

**Comment by JPeer264** [comment]
Hi, thanks for the issue. Can you provide a little snippet so I can add these to my tests?

**Comment by JPeer264** [comment]
released in `rcs-core@2.4.6` and `rename-css-selectors@3.1.4`
