### ISSUE TITLE
selectorLibrary.set() does not check if the given selector is valid.

### ISSUE THREAD

**Issue by emilemil1** [JPeer264/node-rcs-core#75]
Using selectorLibrary.set() does not throw any errors if the given selector is incorrectly formatted.

This can easily lead to some funky bugs, for example if you try to do selectorLibrary.setMultiple(selectorLibrary.getAll()) without specifying addSelectorType: true for getAll(). I was essentially doing this when exporting/importing the library to a disk cache, which eventually led to the cache blowing up with tons of invalid selectors that did nothing except slow down the program. It was also a slightly hard to detect error since everything appeared to function normally until you by chance happened to look at the contents of the cache.

I would suggest doing a quick check that the first character is at least "." or "#".

**Comment by JPeer264** [comment]
Thanks for your issue @emilemil1. 

I see, that is indeed a bug. You think it would be enough to "fail silently", so if I just return before the selector will be registered?

Throwing an error would require an try/catch block around it, which I want to avoid at this point.

**Comment by emilemil1** [comment]
Silent fail is at least better than a hard to detect error. Having return values that return undefined upon failure would probably also work, but that would require more extensive changes.

I'm curious why you need a try/catch, why not just throw and let the error bubble up all the way to the user? You could put the throw under an options flag if that would end up breaking existing code.

**Comment by JPeer264** [comment]
> Silent fail is at least better than a hard to detect error. Having return values that return undefined upon failure would probably also work, but that would require more extensive changes.

Returning the new selector or undefined is indeed a good solution. But I am confused how this should work if the input is an array of selectors. For now I will just ignore invalid selectors, so that you have to error anymore. If a return value is needed it should go into a new issue, but for now I think it is not needed.

> I'm curious why you need a try/catch

With that, I meant the end user needs a try/catch

**Comment by JPeer264** [comment]
Should be fixed in `rcs-core@2.4.7`, if not please open a new issue.
