### ISSUE TITLE
testing keys in a object shouldn't be replaced

### ISSUE THREAD

**Issue by X-Ryl669** [JPeer264/node-rcs-core#83]
Let's say you have this:
```
<style>
.content { color: red }
</style>
<template id='test'></template>
<script>
  // Test if HTML5
  var temp = document.getElementById("test");
  if ("content" in temp)
  {
     // It's HTML5
  }
</script>
```
Here, `content` in `"content" in object` will be replaced but it shouldn't. In fact, as far as I understand it, there is no case where a `"key" in obj` should be replaced, since you should never have CSS class or id or type as the key of some JS objects.
In the recast AST, you'll find that the `String` literal is a child of a `BinaryExpression` with operator `in`. In that case, it easy to fix, replace in `replace/js.js`, code:
```
traverse(ast, {
    pre: (node) => {
      if (node.type === 'Literal' && typeof node.value === 'string') {
// eslint-disable-next-line no-param-reassign
```
with
```
traverse(ast, {
    pre: (node) => {
      // Avoid recursing into a "in" node since it can't be a CSS class or variable. 
      if (node.type === 'BinaryExpression' && node.operator === 'in') 
          return false;
      if (node.type === 'Literal' && typeof node.value === 'string') {
// eslint-disable-next-line no-param-reassign
```

**Comment by JPeer264** [comment]
@X-Ryl669 thanks a lot for making this project better 👍 

Good point. That is actually not impossible that somebody would have selectors as object keys, but I think that would be a kinda anti-pattern. So ya I am totally agreeing on this, could you may add a PR with a test case? (your example is enough for the test case 😊)
