### ISSUE TITLE
Always prints original css to console

### ISSUE THREAD

**Issue by klimashkin** [JPeer264/node-rcs-core#9]
Now it always prints original css (it can be really big) to console, that line:
https://github.com/JPeer264/node-rcs-core/blob/master/lib/options/replace.js#L285

**Comment by JPeer264** [comment]
Whoops, I accidentally pushed that! I will remove that ASAP! Sorry for that.

**Comment by JPeer264** [comment]
@klimashkin Thanks that you reported that. I removed it in v`0.8.3`. If you use any plugins, you can just reinstall the plugin (make sure your npm/yarn cache is empty).

**Comment by klimashkin** [comment]
Thank you!
